//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vita.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ac
        ///act
        ///ad
        ///af
        ///ag
        ///age
        ///air
        ///al
        ///als
        ///am
        ///an
        ///ap
        ///ar
        ///as
        ///at
        ///ate
        ///au
        ///ba
        ///bat
        ///be
        ///ber
        ///bers
        ///bet
        ///bi
        ///ble
        ///bles
        ///bod
        ///bor
        ///bout
        ///but
        ///by
        ///ca
        ///cal
        ///can
        ///cap
        ///car
        ///cat
        ///cate
        ///cen
        ///cent
        ///char
        ///ci
        ///cial
        ///cir
        ///cit
        ///cle
        ///co
        ///col
        ///com
        ///come
        ///con
        ///cor
        ///coun
        ///cov
        ///cu
        ///cul
        ///cus
        ///cy
        ///da
        ///dan
        ///day
        ///de
        ///den
        ///der
        ///ders
        ///di
        ///dif
        ///dis
        ///dle
        ///dy
        ///e
        ///east
        ///ed
        ///ef
        ///el
        ///en
        ///ence
        ///end
        ///ent
        ///er
        ///ered
        ///ern
        ///ers
        ///es
        ///est
        ///et
        ///ev
        ///eve
        ///ex
        ///fa
        ///fac
        ///fect
        ///fer
        ///fi
        ///fin
        ///fish
        ///fix
        ///fol
        ///for
        ///fore
        ///form
        ///ful
        ///gan
        ///gen
        ///ger
        ///gi
        ///g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syllables {
            get {
                return ResourceManager.GetString("Syllables", resourceCulture);
            }
        }
    }
}
